// testUserAssetFetch.ts
import algosdk from 'algosdk';
import { AlgorandClient } from '@algorandfoundation/algokit-utils';
import { FirstStageClient } from './dist/generated/FirstStage.js'; // Your Algokit-generated client

const APP_ID = 3158291365n; // replace with your app ID
const USER_ADDRESS = 'NOLXAGDW6KLLX3GRIVGU72HPHW7WWUN2VE7GUZOLYKEG7FGM6FENVFFEXQ'; // replace with a real address

async function main() {
  // --- Algod configuration ---
  const algodConfig = {
    token: '',
    server: 'https://mainnet-api.algonode.cloud',
    port: '',
  };

  // --- Algod client ---
  const algodClient = new algosdk.Algodv2(algodConfig.token, algodConfig.server, algodConfig.port);

  // --- Algokit client ---
  const algorand = AlgorandClient.fromConfig({ algodConfig });

  // --- App client (generated by Algokit) ---
  const appClient = new FirstStageClient({
    appId: APP_ID,
    algorand,
  });

  try {
    // Fetch reflection preview (ABI read-only call)
    const [tokenReflections, algoReflections] = await appClient.getReflectionPreview({
      sender: USER_ADDRESS,
      args: [APP_ID, USER_ADDRESS],
    });

    console.log('Token reflections (unclaimed):', tokenReflections.toString());
    console.log('ALGO reflections (unclaimed):', algoReflections.toString());
  } catch (err) {
    console.error('Failed to fetch user asset info:', err);
  }
}

main().catch(console.error);
