import type { AlgorandClient } from '@algorandfoundation/algokit-utils';

export interface IFirstStageClient {
  getReflectionPreview(params: { sender: string; args: [bigint, string] }): Promise<[bigint, bigint]>;
  // Add other methods you want to expose
}

/**
 * Dynamically loads the generated FirstStageClient and wraps it in a type-safe interface.
 * Bypasses TS errors in the autogenerated code.
 */
export async function createFirstStageClient(appId: bigint, algorand: AlgorandClient): Promise<IFirstStageClient> {
  const module = await import('./FirstStage.js'); // runtime import
  const client = new module.FirstStageClient({ appId, algorand }) as any;

  return {
    async getReflectionPreview({ sender, args }) {
      // calls original client at runtime
      return client.getReflectionPreview({
        sender,
        args,
      });
    },

    // Add other wrapped methods here as needed
  };
}
